name: Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
    - name: Install Dependencies
      run: |
        npm ci
        npm ci --prefix demo
    - name: Build
      run: npm run build:demo
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: demo/dist/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
